-- =========================================================
-- AEGIS_CC • Migration 0004 • Purchasing Core (Phase 4)
-- Purpose:
--   - Vendors + Catalog (optional)
--   - PR -> PO -> Receiving spine
--   - Links to projects / SOV / timeline tasks
-- Notes:
--   - No security here, Phase 5 will do RLS + RPC-only writes
-- =========================================================

-- -------------------------------
-- 0) Enums
-- -------------------------------
do $$ begin
  create type public.pr_status as enum ('draft','submitted','approved','rejected','cancelled','fulfilled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.po_status as enum ('draft','issued','acknowledged','partially_received','received','closed','cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.receipt_status as enum ('pending','received','reconciled','cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.po_line_status as enum ('open','backordered','cancelled','closed');
exception when duplicate_object then null; end $$;

-- -------------------------------
-- 1) Vendors
-- -------------------------------
create table if not exists public.vendors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  trade text null, -- electrical, gear, lighting, concrete, etc (simple text for now)
  phone text null,
  email text null,
  website text null,

  address1 text null,
  address2 text null,
  city text null,
  state text null,
  zip text null,

  payment_terms text null, -- "Net 30", "COD", etc
  is_active boolean not null default true,

  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists vendors_name_uq on public.vendors (lower(name));

create table if not exists public.vendor_contacts (
  id uuid primary key default gen_random_uuid(),
  vendor_id uuid not null references public.vendors(id) on delete cascade,
  name text not null,
  title text null,
  phone text null,
  email text null,
  is_primary boolean not null default false,
  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists vendor_contacts_vendor_id_idx on public.vendor_contacts(vendor_id);

-- -------------------------------
-- 2) Material / Item Catalog (optional but helpful)
-- -------------------------------
create table if not exists public.material_catalog_items (
  id uuid primary key default gen_random_uuid(),
  sku text null,               -- vendor SKU or internal SKU
  description text not null,
  manufacturer text null,
  model text null,
  uom text null,               -- EA, FT, LF, BOX, etc
  category text null,          -- conduit, wire, devices, gear, lighting
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists material_catalog_desc_idx on public.material_catalog_items using gin (to_tsvector('english', description));

-- -------------------------------
-- 3) Purchase Request (PR) = internal demand
-- -------------------------------
create table if not exists public.purchase_requests (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,

  pr_number text not null, -- generated by RPC in Phase 5
  status public.pr_status not null default 'draft',

  needed_by_date date null,
  priority text null,      -- simple text: normal, hot, emergency

  requested_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz null,

  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists pr_number_uq on public.purchase_requests (pr_number);
create index if not exists pr_project_id_idx on public.purchase_requests(project_id);
create index if not exists pr_status_idx on public.purchase_requests(status);

create table if not exists public.purchase_request_lines (
  id uuid primary key default gen_random_uuid(),
  purchase_request_id uuid not null references public.purchase_requests(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,

  catalog_item_id uuid null references public.material_catalog_items(id) on delete set null,
  description text not null, -- free text fallback

  qty numeric not null default 0,
  uom text null,

  -- Optional cost hinting
  est_unit_cost numeric null,
  est_ext_cost numeric generated always as (coalesce(qty,0) * coalesce(est_unit_cost,0)) stored,

  -- Optional linking
  sov_item_id uuid null references public.sov_items(id) on delete set null,
  timeline_task_id uuid null references public.timeline_tasks(id) on delete set null,

  is_active boolean not null default true,
  sort_order int not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists pr_lines_pr_id_idx on public.purchase_request_lines(purchase_request_id);
create index if not exists pr_lines_project_id_idx on public.purchase_request_lines(project_id);

-- -------------------------------
-- 4) Purchase Order (PO) = external commitment
-- -------------------------------
create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  vendor_id uuid not null references public.vendors(id) on delete restrict,

  po_number text not null, -- generated by RPC in Phase 5
  status public.po_status not null default 'draft',

  issued_at timestamptz null,
  acknowledged_at timestamptz null,

  ship_to_name text null,
  ship_to_address1 text null,
  ship_to_address2 text null,
  ship_to_city text null,
  ship_to_state text null,
  ship_to_zip text null,

  needed_by_date date null,
  freight_est numeric null default 0,
  tax_est numeric null default 0,

  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists po_number_uq on public.purchase_orders (po_number);
create index if not exists po_project_id_idx on public.purchase_orders(project_id);
create index if not exists po_vendor_id_idx on public.purchase_orders(vendor_id);
create index if not exists po_status_idx on public.purchase_orders(status);

create table if not exists public.purchase_order_lines (
  id uuid primary key default gen_random_uuid(),
  purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,

  pr_line_id uuid null references public.purchase_request_lines(id) on delete set null,

  catalog_item_id uuid null references public.material_catalog_items(id) on delete set null,
  description text not null,

  qty numeric not null default 0,
  uom text null,

  unit_cost numeric not null default 0,
  ext_cost numeric generated always as (coalesce(qty,0) * coalesce(unit_cost,0)) stored,

  status public.po_line_status not null default 'open',

  -- optional accounting attribution
  sov_item_id uuid null references public.sov_items(id) on delete set null,
  timeline_task_id uuid null references public.timeline_tasks(id) on delete set null,

  is_active boolean not null default true,
  sort_order int not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists po_lines_po_id_idx on public.purchase_order_lines(purchase_order_id);
create index if not exists po_lines_project_id_idx on public.purchase_order_lines(project_id);

-- -------------------------------
-- 5) Receiving (what actually arrived)
-- -------------------------------
create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  vendor_id uuid null references public.vendors(id) on delete set null,
  purchase_order_id uuid null references public.purchase_orders(id) on delete set null,

  receipt_number text not null, -- generated by RPC in Phase 5
  status public.receipt_status not null default 'pending',

  received_at timestamptz null,
  received_by uuid references public.profiles(id) on delete set null,

  location text null, -- "Lancaster warehouse", "Jobsite", etc
  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists receipt_number_uq on public.receipts (receipt_number);
create index if not exists receipts_project_id_idx on public.receipts(project_id);
create index if not exists receipts_po_id_idx on public.receipts(purchase_order_id);

create table if not exists public.receipt_lines (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null references public.receipts(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,

  purchase_order_line_id uuid null references public.purchase_order_lines(id) on delete set null,

  description text not null,
  qty_received numeric not null default 0,
  uom text null,

  condition text null, -- "good", "damaged", etc
  notes text null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null
);

create index if not exists receipt_lines_receipt_id_idx on public.receipt_lines(receipt_id);
create index if not exists receipt_lines_po_line_id_idx on public.receipt_lines(purchase_order_line_id);

-- =========================================================
-- End 0004
